#!/usr/bin/env bash

# run the script to set up the dev database
psql -X -U postgres -d proddb -f ./setup_dev_db.sql

#run the script to update the dev db with the prod schema and data
./update_dev_db_schema