#!/usr/bin/env bash
# run this script to (re-)populate local developer database tables with current data 
# from the production database, according to sampling logic defined in the SQL script

# run the SQL script to populate local developer database tables with foreign data from production
psql -X -U postgres -d devdb -f ./populate_dev_db.sql

# run the SQL script to set up the sequences correctly for local tables
psql -X -U postgres -d devdb -f ../update_sequences.sql

# update the devdb dump file
pg_dump -N '*prod*' -N 'fdw_setup' -e 'plpgsql' -T 'postgres_fdw' -U postgres -d devdb > devdb.sql