#!/usr/bin/env bash

# run the script to populate local dev db prod schema replica with foreign data from prod
psql -X -U postgres -d devdb -f ./populate_dev_db.sql

# run the script to set up the sequences
psql -X -U postgres -d devdb -f ../update_sequences.sql

# update the devdb dump file
pg_dump -N '*prod*' -N 'fdw_setup' -e 'plpgsql' -T 'postgres_fdw' -U postgres -d devdb > devdb.sql